(()=>{
const svg=`<svg viewBox="0 0 72 72" role="img" aria-label="Emblème médical de Pik" xmlns="http://www.w3.org/2000/svg"><defs><radialGradient id="pg" cx="35%" cy="28%"><stop offset="0" stop-color="#244c37"/><stop offset="1" stop-color="#0b1a12"/></radialGradient><filter id="ps"><feDropShadow dx="0" dy="0" stdDeviation="3" flood-color="#4fd28a" flood-opacity=".55"/></filter></defs><circle cx="36" cy="36" r="30" fill="url(#pg)" stroke="#f4f7f2" stroke-width="3"/><circle cx="36" cy="36" r="24" fill="none" stroke="#4fd28a" stroke-width="1.5" opacity=".65"/><path d="M31 18h10v13h13v10H41v13H31V41H18V31h13z" fill="#ed5c61" stroke="#fff" stroke-width="1.5" filter="url(#ps)"/><path d="M20 57c7-5 13-6 20-3 4 2 8 2 12 0" fill="none" stroke="#4fd28a" stroke-width="2" stroke-linecap="round"/><path d="M23 54c2-6 6-9 12-10" fill="none" stroke="#8ee7b8" stroke-width="1.6" stroke-linecap="round"/></svg>`;
const style=document.createElement('style');style.textContent=`
/* header-silas-exact */
.identity:after{content:none!important}.signature-icon{position:absolute;right:13px;top:50%;width:84px;height:84px;transform:translateY(-50%);opacity:.92;filter:drop-shadow(0 0 14px #4fd28a35);pointer-events:none;z-index:1}.signature-icon svg{width:100%;height:100%;display:block}.identity .eyebrow,.identity h1,.identity p,.identity .tag{position:relative;z-index:2}
.turn-conc{min-width:0;border:1px solid #645486;background:linear-gradient(145deg,#211b2d,#14121d);border-radius:11px;padding:7px 10px;text-align:left;cursor:pointer;overflow:hidden;color:inherit}.turn-conc small{display:block;color:#b8a8df;font-size:.65rem;text-transform:uppercase;letter-spacing:.07em}.turn-conc b{display:block;color:#ded3fb;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.turn-conc.none{border-color:#39423e;background:#111917}.turn-conc.none small,.turn-conc.none b{color:var(--muted)}.turn-conc:not(.none){box-shadow:inset 0 0 0 1px #a08ad733,0 0 15px #8c6dc522}
@media(min-width:768px){.top{display:grid!important;grid-template-columns:1.4fr 2fr!important;gap:14px!important;align-items:stretch!important}.identity{padding:18px 100px 18px 18px!important;min-height:0!important;overflow:hidden!important}.identity h1{font-size:clamp(1.8rem,4vw,3rem)!important;line-height:1!important;margin:.25rem 0 .5rem!important}.identity p{font-size:inherit!important;line-height:1.45!important;white-space:normal!important;overflow:visible!important}.identity .tag{margin-top:10px!important;padding:5px 9px!important;font-size:.77rem!important}.vitals{padding:12px!important;display:grid!important;grid-template-columns:2fr repeat(5,1fr)!important;grid-template-rows:auto!important;gap:8px!important;align-items:stretch!important;overflow:visible!important}.vitals>.stat,.vitals>.hpstat{display:block!important;grid-column:auto!important;grid-row:auto!important;min-width:0!important;padding:10px!important;border-radius:12px!important;text-align:left!important;overflow:hidden!important}.vitals>.stat:nth-child(5){display:none!important}.vitals>.hpstat>small{display:block!important;white-space:normal!important}.vitals .hpbox{display:grid!important;grid-column:auto!important;grid-row:auto!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:5px!important;margin:0!important;max-width:none!important}.vitals .hp-actions{display:flex!important;grid-column:auto!important;grid-row:auto!important;gap:5px!important;margin-top:6px!important}.vitals>.stat b{font-size:1.35rem!important;line-height:1.35!important;white-space:nowrap!important}.vitals>.stat small{font-size:.66rem!important;line-height:1.35!important;letter-spacing:.07em!important}.vitals .num{box-sizing:border-box!important;width:100%!important;height:auto!important;min-height:0!important;padding:6px!important;font-size:inherit!important}.vitals .mini{height:auto!important;min-height:0!important;padding:5px 8px!important;font-size:inherit!important}}
@media(min-width:1101px){.turnbar{grid-template-columns:auto repeat(4,minmax(68px,1fr)) minmax(92px,.85fr) minmax(112px,1fr) auto auto auto!important}}
@media(min-width:768px) and (max-width:1100px){.vitals{grid-template-columns:2fr repeat(3,1fr)!important}.turnbar{grid-template-columns:repeat(4,1fr)!important}.turn-conc{grid-column:span 2}.turnbar .next{grid-column:span 2}}
@media(max-width:767px){.signature-icon{width:58px;height:58px;right:8px}.identity{padding-right:76px!important}.turn-conc{grid-column:span 2}}
@media(prefers-reduced-motion:no-preference){.signature-icon{animation:sigFloat 4.5s ease-in-out infinite}@keyframes sigFloat{0%,100%{transform:translateY(-50%)}50%{transform:translateY(calc(-50% - 3px));filter:drop-shadow(0 0 20px #4fd28a42)}}}
`;document.head.appendChild(style);
const mount=()=>{const id=document.querySelector('.identity');if(!id||id.querySelector('.signature-icon'))return false;const d=document.createElement('div');d.className='signature-icon';d.innerHTML=svg;id.appendChild(d);return true};
if(!mount()){const o=new MutationObserver(()=>{if(mount())o.disconnect()});o.observe(document.documentElement,{childList:true,subtree:true})}

const mountTurnConcentration=()=>{const bar=document.getElementById('turnbar')||document.querySelector('.turnbar');if(!bar||document.getElementById('turnConcentration'))return false;const button=document.createElement('button');button.type='button';button.id='turnConcentration';button.className='turn-conc none';button.title='Ouvrir les sorts';button.innerHTML='<small>Concentration</small><b>Aucune</b>';const anchor=document.getElementById('nextTurn')||bar.querySelector('.next');bar.insertBefore(button,anchor||null);const sync=()=>{const pill=[...document.querySelectorAll('#combatGrid .pill.warn')].find(el=>el.textContent.trim().toLowerCase().startsWith('concentration'));const raw=pill?pill.textContent.trim():'';const value=(raw.includes(':')?raw.slice(raw.indexOf(':')+1):raw).trim()||'Aucune';button.querySelector('b').textContent=value;button.classList.toggle('none',value.toLowerCase()==='aucune')};button.addEventListener('click',()=>document.querySelector('.nav button[data-view="spells"]')?.click());const target=document.getElementById('combatGrid')||document.body;new MutationObserver(sync).observe(target,{childList:true,subtree:true,characterData:true});sync();return true};if(!mountTurnConcentration()){const tcObserver=new MutationObserver(()=>{if(mountTurnConcentration())tcObserver.disconnect()});tcObserver.observe(document.documentElement,{childList:true,subtree:true})}


const quickStyle=document.createElement('style');quickStyle.textContent=`
/* quick-slots-ui */
.quick-slots{width:100%;display:flex;align-items:center;gap:9px;margin:0 0 10px;padding:7px 10px;border:1px solid #3d5148;border-radius:12px;background:linear-gradient(135deg,#101b17e8,#151d19e8);color:var(--ink);text-align:left;box-shadow:inset 0 1px #ffffff08}
.quick-slots-label{font-size:.68rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);white-space:nowrap}.quick-slots-values{display:flex;gap:6px;flex-wrap:wrap;margin-left:auto}.quick-slot{border:1px solid #5e5330;border-radius:8px;padding:4px 7px;background:#1e1a10;font-size:.76rem;white-space:nowrap}.quick-slot b{color:#f0d58e;font-size:.84rem}
@media(max-width:767px){.quick-slots{padding:6px 8px;gap:6px}.quick-slots-label{font-size:.61rem}.quick-slots-values{gap:4px}.quick-slot{padding:3px 6px;font-size:.7rem}}
`;document.head.appendChild(quickStyle);
const mountQuickSlots=()=>{const section=document.querySelector('.view[data-view="combat"]'),source=document.getElementById('slotSummary');if(!section||!source||document.getElementById('quickSpellSlots'))return false;const box=document.createElement('button');box.type='button';box.id='quickSpellSlots';box.className='quick-slots';box.title='Ouvrir les sorts';box.innerHTML='<span class="quick-slots-label">Emplacements</span><span class="quick-slots-values"></span>';section.insertBefore(box,section.firstChild);const sync=()=>{const vals=[...source.querySelectorAll('.slot')].map(x=>x.textContent.trim());box.querySelector('.quick-slots-values').innerHTML=vals.map(v=>{const p=v.split(' ').filter(Boolean);return p.length>1?'<span class="quick-slot">'+p[0]+' <b>'+p[1]+'</b></span>':''}).join('')};box.addEventListener('click',()=>document.querySelector('.nav button[data-view="spells"]')?.click());new MutationObserver(sync).observe(source,{childList:true,subtree:true,characterData:true});sync();return true};
if(!mountQuickSlots()){const qsObserver=new MutationObserver(()=>{if(mountQuickSlots())qsObserver.disconnect()});qsObserver.observe(document.documentElement,{childList:true,subtree:true})}


/* combat-damage-only */
const mountCombatDamageOnly=()=>{const grid=document.getElementById('combatGrid');if(!grid)return false;const prune=()=>{[...grid.querySelectorAll('.card h2')].forEach(h=>{if(h.textContent.trim()==='Urgences & soutien'||h.textContent.trim()==='Canalisation')h.closest('.card')?.remove()});const navCombat=document.querySelector('.nav button[data-go="combat"]');if(navCombat)navCombat.textContent='Combat & dégâts'};new MutationObserver(prune).observe(grid,{childList:true,subtree:true});prune();return true};if(!mountCombatDamageOnly()){const cdObserver=new MutationObserver(()=>{if(mountCombatDamageOnly())cdObserver.disconnect()});cdObserver.observe(document.documentElement,{childList:true,subtree:true})}


/* pik-combat-controls-v2 */
const combatControlsStyle=document.createElement('style');combatControlsStyle.textContent=`
.combat-options-card{background:linear-gradient(135deg,#141d19,#101713)!important}.combat-options-card .options{margin-bottom:0}.blessed-auto{border-color:#4fa873!important;box-shadow:0 0 15px #4fd28a25;color:#bdf2d2!important}.new-combat-turn{white-space:nowrap}.ribbon-undo{right:40px!important;top:7px!important;width:auto!important;height:auto!important;border:1px solid #596d64!important;border-radius:8px!important;background:#17231f!important;padding:4px 8px!important;font-size:.72rem!important}
@media(min-width:1101px){.turnbar{grid-template-columns:auto repeat(4,minmax(68px,1fr)) minmax(92px,.85fr) minmax(112px,1fr) auto auto auto!important}}
@media(max-width:767px){.result-ribbon{padding-right:112px!important}}
`;document.head.appendChild(combatControlsStyle);
const mountPikCombatControls=()=>{const grid=document.getElementById('combatGrid'),bar=document.querySelector('.turnbar'),ribbon=document.getElementById('resultRibbon');if(!grid||!bar||!ribbon)return false;
 const reshape=()=>{const title=[...grid.querySelectorAll('.card h2')].find(h=>h.textContent.trim()==='État tactique');if(!title)return;const card=title.closest('.card'),furyText=card.querySelector('#furyToggle')?.textContent||'Fureur des petits +3',blessedText=card.querySelector('#blessedToggle')?.textContent||'Frappes bénies +1d8 (disponible)';card.className='card full combat-options-card';card.innerHTML='<h2>Options offensives</h2><div class="options"><button id="furyToggle" class="toggle" onclick="this.classList.toggle(\'on\')">'+furyText+'</button><button id="manualToggle" class="toggle" onclick="this.classList.toggle(\'on\');this.textContent=this.classList.contains(\'on\')?\'Jet manuel : oui\':\'Jet manuel : non\'">Jet manuel : non</button><span id="blessedToggle" class="on" hidden></span><span class="pill good blessed-auto">Frappes bénies automatique '+(blessedText.includes('utilisée')?'· utilisée ce tour':'· disponible')+'</span></div>'};
 new MutationObserver(reshape).observe(grid,{childList:true,subtree:true});reshape();
 document.getElementById('newCombatTurn')?.remove();const journalTools=document.querySelector('.view[data-view="journal"] .journal-tools');if(journalTools&&!document.getElementById('newCombatJournal')){const b=document.createElement('button');b.type='button';b.id='newCombatJournal';b.className='ability';b.textContent='Nouveau combat';b.setAttribute('onclick','newCombat()');journalTools.insertBefore(b,journalTools.firstChild)}
 if(!document.getElementById('ribbonUndo')){const b=document.createElement('button');b.type='button';b.id='ribbonUndo';b.className='ribbon-undo';b.textContent='↶ Annuler';b.setAttribute('onclick','undo()');ribbon.appendChild(b)}
 return true};
if(!mountPikCombatControls()){const pccObserver=new MutationObserver(()=>{if(mountPikCombatControls())pccObserver.disconnect()});pccObserver.observe(document.documentElement,{childList:true,subtree:true})}

const fav=document.createElement('link');fav.rel='icon';fav.type='image/svg+xml';fav.href='data:image/svg+xml,'+encodeURIComponent(svg);document.head.appendChild(fav);
})();